### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mrmurphy** [xmlet/HtmlFlow#1]
Hey! I'd love to use your library, but I'm not sure how to do some things.
What's the procedure for adding a table?
I noticed that none of your test cases are in the repo. If you've written them, maybe they'd make a good reference for those who want to use it?

**Comment by fmcarvalho** [comment]
@mrmurphy As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by mrmurphy** [comment]
Hi there! Sorry, I haven't used this library since our discussion 12 years ago. Good luck!
