### ISSUE TITLE
Inline SVG from string add to view

### ISSUE THREAD

**Issue by syncros-service** [xmlet/HtmlFlow#101]
I am using a library that can dynamically generate an SVG as a string.
Is it possible to add to a view as HTML string directly? No HTML checking/validation is required.

Example use case:
```java
	final String svgAsString = lib.generate(uuid);
	view
			.div()
				.of(d -> d.appendRawHTML(svgAsString))
			.__();

```
Example generated SVG. I cannot write this to file and link the resource.
I could re-create it via: view.svg() but would require a lot of custom tags and attributes.
```powershell
<svg width="6.588mm" height="11.7mm" viewBox="0 0 6.588 11.7">
  <rect width="0.432" height="11.7" x="0.216" y="0.0" fill="black" />
  <rect width="1.188" height="11.7" x="1.080" y="0.0" fill="black" />
  <rect width="0.432" height="11.7" x="3.456" y="0.0" fill="black" />
  <rect width="1.188" height="11.7" x="4.320" y="0.0" fill="black" />
  <rect width="0.432" height="11.7" x="5.940" y="0.0" fill="black" />
</svg>
```

**Comment by syncros-service** [comment]
I found out you can use .text() which will work

**Comment by fmcarvalho** [comment]
@syncros-service Can you please star HtmlFlow project to raise attention from the community. Thanks

**Comment by fmcarvalho** [comment]
@syncros-service As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@syncros-service Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
