### ISSUE TITLE
Tags gets confused with text

### ISSUE THREAD

**Issue by cohenran** [xmlet/HtmlFlow#103]
This code, produces this nice output:
form
&emsp;    .textarea()
&emsp;&emsp;	  .addAttr("align", "right")
&emsp;&emsp;	  .attrRows(50l)
&emsp;&emsp;	  .attrCols(50l)
&emsp;&emsp;	  .attrId("id")
&emsp;&emsp;	  .attrName("name")
&emsp;&emsp;	  .attrStyle(style)
&emsp;&emsp;	  .text("text")
&emsp;	  .__();
<textarea align="right" rows="50" cols="50" id="id" name="name" style="width: 89%; height: 77px;">
<br><br>
However, this code, produces a problematic output:
<br>
form
<br>&emsp;.textarea()
<br>&emsp;&emsp;	  .addAttr("align", "right")
<br>&emsp;&emsp;	  .attrRows(50l)
<br>&emsp;&emsp;	  .text("text")
<br>&emsp;&emsp;	  .attrCols(50l)
<br>&emsp;&emsp;	  .attrId("id")
<br>&emsp;&emsp;	  .attrName("name")
<br>&emsp;&emsp;	  .attrStyle(style)
<br>&emsp;	  .__();
<br>
<textarea align="right" rows="50">text cols="50" id="id" name="name" style="width: 89%; height: 77px;"
<br>
<br>All I did was move the .text("text") up, and it made it outside of the textarea tag.
<br>It happened with other properties like attrClass.
<br>If it happens because text returns the parent element, maybe an exception should be thrown if I use attr after.

**Comment by fmcarvalho** [comment]
Good catch !!!

And you are right about: _maybe an exception should be thrown if I use attr after._

I will fix it according.

Thanks,
Miguel

**Comment by fmcarvalho** [comment]
Solved on new release 4.2, following your suggestion of throwing an Exception on that case.

**Comment by fmcarvalho** [comment]
@cohenran Can you please star HtmlFlow project to raise attention from the community. Thanks

**Comment by fmcarvalho** [comment]
@cohenran As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@cohenran Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
