### ISSUE TITLE
Nested Table

### ISSUE THREAD

**Issue by pradex** [xmlet/HtmlFlow#18]
Hi,
I think i am missing something but can you please help me understand how can i create nested table.
Something like below? I tried adding table to HtmlTd but that didn't work.

```
<table cellpadding="0" cellspacing="0">
        <tr class="top">
            <td colspan="2">
                <table>
                    <tr>
                        <td class="title">
                            <img src="logo.png" style="width:100%; max-width:300px;" />
                        </td>

                        <td>
                            Invoice #: 123<br />
                            Created: January 1, 2015<br />
                            Due: February 1, 2015
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
</table>
```

**Comment by fmcarvalho** [comment]
Yes you can create a nested table, but you can't do it in a fluent style, because current fluent API of HtmlFlow still not provide it. 

So, the alternative solution is to make something like: 

```java
HtmlTable<T> outerTable = ...
...
HtmlTable<T> nestedTable = new HtmlTable<>(); // create a new Table
outerTable.tr().td().addChild(new HtmlTable<>()); // Add a row, with a single TD, and the nested table inside it
nested.tr(). ... // proceed to add whatever you want 
```
In truth with the **command** API you have total flexibility to add what you want. The alternative **fluent** API should follow the HTML grammar, but it is not completely implemented and has limitations. We have been adding new methods to the fluent API according to new needs.

Maybe we should open an Issue to collect the methods that are most used and missing in the fluent API to include that in next fixes.

**Comment by fmcarvalho** [comment]
@pradex  Since release 2.0 of HtmlFlow we already support building nested tables in fluent way.

We add a unit test with an example of a nested table according to the use case that you presented in your original post. Check it [here](https://github.com/xmlet/HtmlFlow/blob/master/src/test/java/htmlflow/test/HtmlTables.java#L151). It is like: 

```java
static final HtmlView nestedTable = HtmlView
    .html()
        .body()
            .table()
                .tr()
                    .attrClass("top")
                    .td()
                        .attrColspan("2")
                        .table()
                            .tr()
                                .td()
                                    .attrClass("title")
                                    .img()
                                        .attrSrc("logo.png")
                                        .attrStyle("width:100%; max-width:300px;")
                                    .º() // img
                                .º() // td
                            .º() // tr
                        .º() // table
                    .º() // td
                    .td()
                        .text("Invoice #: 123")
                        .br().º()
                        .text("Created: January 1, 2015")
                        .br().º()
                        .text("Due: February 1, 2015")
                    .º() // td
                .º() // tr
            .º() // table
        .º() // body
    .º(); // html
```

**Comment by fmcarvalho** [comment]
@pradex As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
