### ISSUE TITLE
message box with text content display on click

### ISSUE THREAD

**Issue by madhuri1ch** [xmlet/HtmlFlow#31]
can you please help how I can display a content on message box, once user clicks on data in a cell of table using your framework.

**Comment by fmcarvalho** [comment]
@madhuri1ch, you can do it by using the  method `attrOnclick(String)` such as: 

```java
Tr tr = ...
Td td = tr.td();
td.text(...);
td.attrOnclick("alert('Cell clicked!')");
```

Every element provides the set of allowed attributes through the methods `attr...()` where `...` is the corresponding HTML attribute for that element.

Alternatively, you can give it a unique `id ` through the method `attrId(...)` and then add a convenient listener in a JavaScript file linked to this document through: 
```java
...
.head()
.script()
.attrType(EnumTypeScript.TEXT_JAVASCRIPT)
.attrSrc("path-to-javascript-file");
```

Hope this help you to solve your issue.

**Comment by madhuri1ch** [comment]
Thanks for your reply.
  .td().attrClass("tg-2thk").text("New").attrOnclick("test").º()
 my requirement is to show the message "test" when user clicks on 'New' in a table cell. However the above line does not do anything. Please let me know where I am wrong.

**Comment by madhuri1ch** [comment]
Thank you.This helped

**Comment by fmcarvalho** [comment]
Nice. Can you @madhuri1ch please add a star to HtmlFow stargazers. Thanks

**Comment by fmcarvalho** [comment]
@madhuri1ch As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@madhuri1ch Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
