### ISSUE TITLE
Option to disable pretty print / intendation

### ISSUE THREAD

**Issue by theotherp** [xmlet/HtmlFlow#46]
I'm generating an HTML file with `<pre>` elements. The first line of the content is incorrectly indented. Is there an option to prevent that?

**Comment by fmcarvalho** [comment]
Ok, I see your problem. What kind of disable indentation feature are you thinking? 

1. Do you want to disable indentation at all and print whole document without any indentation?

2. Or do you want stop indentation at certain point (e.g. before invoking `pre()`) and then enable indentation again?

**Comment by theotherp** [comment]
I don't really need pretty HTML at all so I don't have a preference. I guess ideally both, but disabling it globally would probably be easier. Looking at the code you would just have to skip the indent call.

**Comment by fmcarvalho** [comment]
Ok, I will include that feature for release 3.3. Can you please include here a small function with your use case of the `pre` element for unit testing?

**Comment by theotherp** [comment]
```
@Test
    public void bla() throws Exception {
        HtmlView htmlView = new HtmlView<>();
        htmlView.body().pre().text("Some text");
        String s;
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            htmlView.setPrintStream(new PrintStream(out));
            htmlView.write();
            s = out.toString();
        }

        assertTrue(s.replaceAll("<pre>\\s+", "<pre>").contains("<pre>Some text"));

        assertFalse(s.contains("\tSome text"));
        assertTrue(s.contains("<pre>Some text"));
    }
```

**Comment by fmcarvalho** [comment]
@theotherp which version of HtmlFlow are you using?

**Comment by fmcarvalho** [comment]
@theotherp can you please tell me which version of HtmlFlow are you using?

**Comment by theotherp** [comment]
2.0

**Comment by theotherp** [comment]
I just realized how crazy it is to write a feature request when I don't use the newest version... I'll try to update and see if it works. Sorry about that...

**Comment by fmcarvalho** [comment]
@theotherp I have just released a new version with support to disable pretty print / indentation. Basically now we provide a new [`setIndented(boolean isIndented)`](https://github.com/xmlet/HtmlFlow/blob/master/src/main/java/htmlflow/HtmlView.java#L135) setter in `HtmView`. Note that `HtmlView` instances are immutable, so whenever you call `setIndented` it returns a new `HtmlView` object rather than changing the existing one.

Here in [HtmlWithoutIndentation.java](https://github.com/xmlet/HtmlFlow/blob/master/src/test/java/htmlflow/test/views/HtmlWithoutIndentation.java) you can find some use cases of `setIndented` usage.

Sorry for this late feature but I have been overwhelmed and I also included some other required fixes on this version.

By the way, I think you are not an HtmlFlow stargazer. Could you please give us a star?

Best regards,
Miguel

**Comment by theotherp** [comment]
Thank you, will give it a try.

**Comment by fmcarvalho** [comment]
@theotherp As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@theotherp Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.

**Comment by theotherp** [comment]
Will do.
