### ISSUE TITLE
Petclinic (Java pet store) sample application with HtmlFlow

### ISSUE THREAD

**Issue by damir78** [xmlet/HtmlFlow#48]
Hi @fmcarvalho

thank you for you template engine. Very interesting approach.

Can you provide a standard example Petclinic implemented with "login-registration" (spring security) ? **PETCLINIC** 

The developer need to know how to implement the standard functionality with HtmlFlow.

Read more about petclinic or pet store app: 
1) spring implementation https://projects.spring.io/spring-petclinic/
2) j2ee implementation https://antoniogoncalves.org/2012/06/25/yet-another-petstore/
https://www.oracle.com/technetwork/java/petstore1-3-1-02-139690.html

Regards

**Comment by fmcarvalho** [comment]
I like your suggestion! In the meanwhile I am overwhelmed! I still have an HtmlFlow release in progress and a new feature to include, regarding another open Issue. 

I will try to address this Issue on next week.

Thanks for your feedback.

**Comment by fmcarvalho** [comment]
@damir78 We have provided in [github.com/xmlet/spring-petclinic](https://github.com/xmlet/spring-petclinic)
a standard implementation of the sample Spring-based pet clinic web application integrated
with HtmlFlow views.

We have replaced the Thymeleaf template engine with HtmlFlow.

This project defines templates as first-class functions and exploit all the Java language features
and suppress auxiliary Spring infrastructures, such as `ModelAndView`, `ViewResolver` and others.
Thus, we removed from the unit tests all validations regarding these mechanics.

It will be interesting to have a specific spring `ViewResolver` for HtmlFlow that deals with errors in spring and allows more assertions in unit tests.  I will open an issue for that. For now, I don't have enough knowledge to develop that.

The most consuming task regarding the translation of the Thymeleaf templates to HtmlFlow is already done graceful to the new _Flowifier_ tool provided since release 3.4 of HtmlFlow. I think those new sample HtmlFlow views for pet clinic will give a big effort to anyone starting with HtmlFlow.

**Comment by fmcarvalho** [comment]
@damir78 Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
