### ISSUE TITLE
Links to HtmlLists and HtmlTables are broken

### ISSUE THREAD

**Issue by volgin** [xmlet/HtmlFlow#50]

**Comment by volgin** [comment]
These links are broken in Readme.

**Comment by gouessej** [comment]
Hello

You're right, those links are broken in the readme file, the subdirectory named "views" is missing, they are here:
https://github.com/xmlet/HtmlFlow/blob/master/src/test/java/htmlflow/test/views/HtmlLists.java
https://github.com/xmlet/HtmlFlow/blob/master/src/test/java/htmlflow/test/views/HtmlTables.java

**Comment by gouessej** [comment]
@volgin Thank you, it's fixed in my pull request.

**Comment by fmcarvalho** [comment]
@gouessej I have merged your pull request to development branch to be included in next release, which I hope to be launched soon.

**Comment by gouessej** [comment]
@fmcarvalho Thank you.

**Comment by fmcarvalho** [comment]
Published on https://github.com/xmlet/HtmlFlow/releases/tag/htmlflow-3.4

**Comment by fmcarvalho** [comment]
@volgin As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@volgin Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
