### ISSUE TITLE
Misunderstanding of how to use printStream to stream html

### ISSUE THREAD

**Issue by pedromvu** [xmlet/HtmlFlow#66]
So I had everything working using render(), when I ran into issues and decided to change to output into a file when I realized just adding the printStream and calling write at the end didn't work.

Debugging the code I realized all the builder code is executing everything eagerly building some StringBuilder as you add html tags, and all the buffer gets discarded as soon as I call setPrintStream.

So the only solution I found was to set the printStream right before I start building the Html:

`
var view = (HtmlView<?>) StaticHtml.view().setPrintStream(ps);
var html = view.html();
`

But not sure the method returns a less specific type, thats why I had to add the cast, but in the end it works.

Is this how it is supposed to work? because from the documentation I assumed you could decide how to render it at the end, and so I assumed everything would run lazily like Java streams.

**Comment by pedromvu** [comment]
So decided to check the tests and realized that for html to build lazily I need to use the version of view() that takes a consumer, also that there is a version that takes the printStream to avoid needing the cast if I used my current approach, I guess I didn't read the documentation properly.

**Comment by fmcarvalho** [comment]
Please let me know If is is there any section of documentations that you think that should be clarified! 

The documentation has been built from an implementation point of view and it lacks some feature details from an end user view. 

I will try to improve the documentation with users suggestions.

**Comment by fmcarvalho** [comment]
@pedromvu As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@pedromvu Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
