### ISSUE TITLE
Could Taskview return always the same HtmlBody instead of creating?

### ISSUE THREAD

**Issue by kenji-getpowered** [xmlet/HtmlFlow#8]
use case:

```
    taskView.body()
    .div()
      .classAttr(divClass)
      .idAttr(divId)
      .addAttr("toto", "tutu").form("/action.do");

     taskView.body()
      .div()
      .idAttr("id2")
      .addAttr("toto", "tutu").form("/action2.do");
```

Proposition 

``` java
public class HtmlView<T> extends HtmlWriterComposite<T, HtmlView<T>>{

     public HtmlHead<T> head(){return addChild(new HtmlHead<T>());}

    private HtmlBody body = null;
    public HtmlBody<T> body() {
        if (body == null) {
            body = addChild(new HtmlBody<T>());

        }
        return body;
    }
```

**Comment by fmcarvalho** [comment]
I cannot totally agree with your idea for a couple of reasons. But I think that I have an alternative approach. First, what I don't like too much:

   * duplicating the storage for HTML elements both in parent class `HtmlWriterComposite` and into an additional body field of the derived class. That could be error prone.

   * duplicating the semantics of the `body()` method. These kind of methods are factories and I think we should not mess up their meaning: between a factory and a getter.

My suggestion would be to create an additional method in `HtmlWriterComposite`: 

```java
<S extends HtmlWriter<?>> S getChild(String id)
```

Or even: 
```java
<S extends HtmlWriter<?>> S getChild(String id, Class<S> childClass)
```

Then in `HtmlView` you could create an overloaded method `body(String id)` or `getBody(String id)` (to clearly distinguish from `body()`) that would reuse the base method `getChild(…)` to return the body element with the specified id. What do you think?

**Comment by kenji-getpowered** [comment]
I join you on that. Using an id system was my second approach. I have to think a little bit more about the getChild()/body(String id) approach but I think it could answer my requirements.

Do you agree on this :
We cannot have 2 elements with the same id in an html page?
We might want to add additional elements to a parent (use case : We want to add a table and a form in the DIV element), with this code, it is not possible)

I proposed to add the body system be cause, here we have a directional graph (with children field), we cannot go  up to add a second child to a node. Using the body approach allowed to add nested elements to the body without implementing a complicated bi directional graph or whatever.

**Comment by fmcarvalho** [comment]
I am preparing a detailed response with my proposal. I will post it in 5 minutes.

**Comment by fmcarvalho** [comment]
> We cannot have 2 elements with the same id in an html page?

Ideally we shouldn’t. But it is not easy. However, we can implement that feature in part and leave the rest for the future. 

What I mean is that it could be easy to validate if an element already exists with the same id in the parent’s `children` storage. However, we should continue looking for that id in the parent’s parent and so on, until we reach the root element (eventually the `HtmlView`). And this is not trivial. Once, the `children` is a `List<HtmlWriter<?>>` then we must check if every element is a composite, or not, to proceed the lookup. I don’t like it and moreover, it will add a performance overhead.

Another alternative approach is to postpone the verification to write time. Thus, when we are writing the HTML to the PrintStream we can check if there are repeated ids and throw an error in that case.

Nevertheless, I think that this is not a priority feature and for now I would just consider that a composite has NOT two child elements with the same id.

> We might want to add additional elements to a parent 
> (use case : We want to add a table and a form in the DIV element), 
> with this code, it is not possible)

I implemented my previous proposal and with that I can write: 

```java
    taskView.body()                 // create the body
            .div()                  // add a div to the body
            .classAttr(divClass)
            .idAttr(divId)         // add the divId to the previous div
            .addAttr("toto", "tutu")
            .form("/action.do");   // add a form to the div with divId

    taskView.getBody()     // get a body with any Id
            .getDiv(divId) // from the body, get the div with divId
            .table()       // add a table to the div with divId
            .tr();
```

To that end I had the following method to `HtmlWriterComposite`:
```java
protected <S extends HtmlWriter<?, S>> S getChild(Optional<String> id, Class<S> childClass) {
		Predicate<HtmlWriter<?, ?>> p = elem -> elem.getClass() == childClass;
		p = p.and(elem -> !id.isPresent() || id.get().equals(elem.getIdAttribute()));
		return (S) children.stream().filter(p).findFirst().get();
	}
/// NOTE: I did not test this code
```
I choose the second option of my first proposal, because we will need to return a concrete element of type `S`. But, this implies another modification, because we need to invoke `elem.getIdAttribute()` for every element in `children`. Once `children` is a `List<HtmlWriter<?>>` we do NOT have the ` getIdAttribute()` on its elements. So,  the easiest way that I find to solve this problem was to **modify** `HtmlWriter` declaration to: 

```java
/**
 * @param <T> The domain object type
 * @param <S> The type derived from HtmlWriter
 */
interface HtmlWriter<T, S extends HtmlWriter<T, S>> extends HtmlSelector<S>`
```

I don’t like it very much. Ideally we should have a class between `HtmlWriter` and `HtmlWriterComposite`  that implements both interfaces: `HtmlWriter` and `HtmlSelecter`. But for now, that was the quickest way to solve it. 

And finally we can add the desired methods to the concrete elements:

```java
public class HtmlView<T> extends HtmlWriterComposite<T, HtmlView<T>>{
…
	public HtmlBody<T> getBody() {return getChild(Optional.empty(), HtmlBody.class);}
```

and: 

```java
public class HtmlBody<T> extends HtmlWriterComposite<T, HtmlBody<T>>{
…
    public HtmlDiv<T> getDiv(String id) {return getChild(Optional.of(id), HtmlDiv.class);}
```

**Comment by kenji-getpowered** [comment]
hi again,

The solution 
```java
  taskView.body()                 // create the body
            .div()                  // add a div to the body
            .classAttr(divClass)
            .idAttr(divId)         // add the divId to the previous div
            .addAttr("toto", "tutu")
            .form("/action.do");   // add a form to the div with divId

    taskView.getBody()     // get a body with any Id
            .getDiv(divId) // from the body, get the div with divId
            .table()       // add a table to the div with divId
            .tr();
```
is fine by as it answers my usage.


> What I mean is that it could be easy to validate if an element already exists with the same id in the parent’s children storage. However, we should continue looking for that id in the parent’s parent and so on, until we reach the root element (eventually the HtmlView). And this is not trivial. Once, the children is a List<HtmlWriter<?>> then we must check if every element is a composite, or not, to proceed the lookup. I don’t like it and moreover, it will add a performance overhead.

What I had in mind is more like a context associated to the HtmlView. A bit like an application context and beans in Spring or CDI. The method addChild() could save a reference Map <id, element>, so we can do anywhere 
```
taskView.getDiv(divId)
```
Well this is just an idea, not a real need anyway. I am trying to keep id simple.

**Comment by fmcarvalho** [comment]
I merged your last commit from kenji-getpowered/HtmlFlow/tree/master/, because I would like to make some general fixes.

**Comment by fmcarvalho** [comment]
Since release 2.0, HtmlFlow follows the Html5.xsd specification and all Element classes are generated with automated xmlet support. So,  now we have a generic way of looking for an element given a `Predicate` which is available in all element classes:

```java
<R extends Element> Stream<R> find(Predicate<Element> var1);
``` 
Although it is not so easy as the first proposed approach, such as `HtmlDiv<T> getDiv(String id)`, yet the new 2.0 features also provide an easy way of navigating in html elements without `ids`. Regarding the OP use case which creates undesirable body elements twice :
```java
    taskView.body()
    .div()
      .classAttr(divClass)
      .idAttr(divId)
      .addAttr("toto", "tutu").form("/action.do");

     taskView.body() // !!!!! Creating a 2nd body
      .div()
      .idAttr("id2")
      .addAttr("toto", "tutu").form("/action2.do");
```

now we can avoid it in the following way since release 2.0:

``` java
taskView
  .body()
    .div()
      .attrClass(divClass)
      .attrId(divId)
      .addAttr(new BaseAttribute("tutu", "toto"))
    .º() // div
    .div() 
      .attrId("id2")
      .addAttr(new BaseAttribute("tutu", "toto"))
          .form("/action2.do");
```
