### ISSUE TITLE
Enhance documentation with complete list of methods

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#96]
I understand that most of the api surface is generated based on XSD And that htmlFlow is a nice tool when using intelisence.

But some of us don't use language server and might prefer an exaustive documentation of the api.

For exemple a complete liste of elements, and a complete list of attributes would be a nice addition to the documentation.

But since the app is based on an xsd, the documentation  should be too, is there a way to extract a complete liste of both sets?

**Comment by fmcarvalho** [comment]
You may find the javadocs for every Element implementation here: https://repo1.maven.org/maven2/com/github/xmlet/htmlApiFaster/1.0.12/htmlApiFaster-1.0.12-javadoc.jar

And you have a listing in org/xmlet/htmlapifaster/package-summary.html

Off course it misses a description because it is auto generated. 

Is this kind of HTML docs you are looking for?

**Comment by fmcarvalho** [comment]
@benzen Is this enough? https://javadoc.io/doc/com.github.xmlet/htmlApiFaster/latest/org/xmlet/htmlapifaster/package-summary.html

**Comment by benzen** [comment]
Perfect for me

**Comment by fmcarvalho** [comment]
Version 4.1 released and solve this issue.
